apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-blog
  labels:
    app: ghost
  namespace: ghost-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: blog
        image: ghost
        imagePullPolicy: Always
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://www.kkovach.com
        volumeMounts:
          - mountPath: /var/lib/ghost/content
            name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: ghost-pvc