apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    release: wikijs
  name: wikijs-postgresql-headless
  namespace: wiki-js
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: postgresql
    release: wikijs
  sessionAffinity: None
  type: ClusterIP