apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: wikijs
    app.kubernetes.io/name: wiki
    app.kubernetes.io/version: latest
  name: wikijs
  namespace: wiki-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: wikijs
      app.kubernetes.io/name: wiki
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: wikijs
        app.kubernetes.io/name: wiki
    spec:
      containers:
      - env:
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: wikijs-postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: wiki
        - name: DB_USER
          value: postgres
        - name: DB_SSL
          value: "false"
        - name: DB_SSL_CA
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: wikijs-postgresql
        - name: HA_ACTIVE
          value: "false"
        image: requarks/wiki:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: wiki
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: wikijs
      serviceAccountName: wikijs
      terminationGracePeriodSeconds: 30