apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql
    release: wikijs
  name: wikijs-postgresql
  namespace: wiki-js
spec:
  clusterIP: 10.43.130.79
  clusterIPs:
  - 10.43.130.79
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: postgresql
    release: wikijs
    role: master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
